<?php
// Starting session
session_start();

//Including utils and establishing connection 
include "../utils/helper.php";
include "../utils/connect.php";
?>

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="createAccount.css?v=<?php echo time(); ?>">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>Create Account</title>
</head>

<body>
    <div id="header">
        <img src="../Icons/university.svg" height="50" width="50" style="margin-left: 10px; margin-top: 10px;">
        <label style="font-size: large;"> University Internet Gateway</label>
    </div>
    <div class="center">
        <div class="container">
            <div class="text" margin="auto">
                Create Account</div>
            <form action="" method="post">
                <div class="data" id="FirstName">
                    <label>First Name</label>
                    <input type="text" name="FName" required>
                </div>
                <div class="data">
                    <label>Last Name</label>
                    <input type="text" name="LName" required>
                </div>
                <div class="data">
                    <label>Username</label>
                    <input type="text" name="username" required>
                </div>
                <div class="data">
                    <label>Password</label>
                    <input type="password" name="password" required>
                </div>
                <div class="data">
                    <label>Account Type</label>
                    <select name="acctype" class="dropdown" size="1">
                        <option value="student"> Student</option>
                        <option value="instructor"> Instructor</option>
                        <option value="secretary"> Secretary</option>
                    </select>
                </div>
                <div class="btn">
                    <button type="submit">CREATE ACCOUNT!</button>

                </div>
                <?php
                if (isset($_SESSION["error"])) {
                    $error = $_SESSION["error"];
                    echo "<label class='error_message'>$error</label>";
                    unset($_SESSION["error"]);
                }
                ?>
            </form>
        </div>
    </div>
    <div id="footer"></div>
</body>
<?php
// Obtaining user inputs via HTML form
$username = $_POST["username"];
$password = $_POST["password"];
$FName = $_POST["FName"];
$LName = $_POST["LName"];
$Acctype = $_POST["acctype"];

// Check if username exists or not
$isExists = check_username($conn, $Acctype, $username);
if ($isExists and ($username != null or $password != null)) {
    $_SESSION["error"] = "Username already exists";
    header("Location: http://localhost/universitywebproject/login/createAccount.php");
} else {
    // Query for inserting user to the related user type. By defual instructor and student 
    //  numbers generated by a function in helper.php
    if ($Acctype == 'student') {
        $generatedStudentNum = generated_student_number($conn);
        $GPA = rand(0, 40) / 10;
        $randClass = rand(1,4);
        $sql = "INSERT INTO `student`(`Username`, `Password`, `FName`, `LName`, `GPA`, `StudentNumber`, `Class`) VALUES ('$username','$password','$FName ','$LName', $GPA, $generatedStudentNum, $randClass);";
    }
    if ($Acctype == 'instructor') {
        $generatedInstructorNum = generated_instructor_number($conn);
        $sql = "INSERT INTO `instructor`(`Username`, `Password`, `FName`, `LName`, `InstructorNumber`) VALUES ('$username','$password','$FName ','$LName', $generatedInstructorNum);";
    }
    if ($Acctype == 'secretary') {
        $sql = "INSERT INTO `secretary`(`Username`, `Password`, `FName`, `LName`) VALUES ('$username','$password','$FName ','$LName');";
    }
    // Redirecting user to the main.php
    if ($conn->query($sql) === TRUE) {
        header("Location: http://localhost/universitywebproject/login/main.php");
    } else {
        console_log($conn->error);
    }
}

// Closing connection
$conn->close();
?>

</html>